#!/usr/bin/env python3
"""Concatenate the skill into a single paste-in prompt.

The skill is the source of truth. This generates dist/prompt.md from it, so the
copy-paste version can never drift from the installed version. Run it after any
edit to SKILL.md or references/, or let the GitHub Action run it on push.
"""
import pathlib, datetime, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL = ROOT / "skills" / "product-manager-resume-builder"
OUT = ROOT / "dist" / "prompt.md"

# Reference files in the order a session encounters them.
ORDER = [
    ("targeting.md", "Targeting: role, level, and company"),
    ("markets.md", "Market conventions and house rules"),
    ("transitions.md", "Transitioning into PM from another function"),
    ("breaking-in.md", "Breaking in early career"),
    ("from-scratch.md", "Building from scratch"),
    ("bullets.md", "Bullet mechanics"),
    ("templates.md", "Templates, length, and formatting"),
    ("writing-style.md", "Writing style: sounding like the candidate"),
    ("jd-and-ats.md", "Reading a job description, and surviving the parser"),
]

def strip_frontmatter(text):
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[end + 4:].lstrip("\n")
    return text

def demote(text, levels=1):
    """Push every heading down so appendices nest under the main document."""
    return re.sub(r"^(#{1,5}) ", lambda m: "#" * (len(m.group(1)) + levels) + " ", text, flags=re.M)

def make_zip():
    """Package the skill folder for upload to assistants that take a ZIP.

    Zips the skill directory itself, so the archive contains
    product-manager-resume-builder/SKILL.md and .../references/*.md.
    Zipping the repo root instead is what drops the reference files.
    """
    import zipfile
    out = ROOT / "dist" / "product-manager-resume-builder.zip"
    out.parent.mkdir(parents=True, exist_ok=True)
    # Fixed timestamps make the archive byte-identical for identical content.
    # Without this the zip differs on every build and, being binary, conflicts
    # whenever CI and a local build touch it at the same time.
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(SKILL.rglob("*.md")):
            info = zipfile.ZipInfo(str(f.relative_to(SKILL.parent)), date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, f.read_bytes())
    names = zipfile.ZipFile(out).namelist()
    assert any(n.endswith("SKILL.md") for n in names), "SKILL.md missing from archive"
    assert sum("/references/" in n for n in names) >= 8, "reference files missing from archive"
    print(f"wrote {out.relative_to(ROOT)} ({len(names)} files)")


def main():
    skill = strip_frontmatter((SKILL / "SKILL.md").read_text(encoding="utf-8"))
    # The skill defers to reference files by name. In a single prompt they are inline.
    skill = skill.replace("Read these when the phase calls for them, not up front.",
                          "These are inlined below as appendices. Consult them at the phase named.")
    skill = re.sub(r"`references/([a-z-]+)\.md`", r"Appendix: \1", skill)

    parts = [
        "# Product Manager Resume Builder",
        "",
        "> Generated from the skill at skills/product-manager-resume-builder/.",
        "> Do not edit this file. Edit the skill and run scripts/build-prompt.py.",
        f"> Last generated {datetime.date.today().isoformat()}.",
        "",
        "Paste everything below into Claude, ChatGPT, Gemini, or any capable model,",
        "then attach or paste your current resume. If you have no resume yet, say so.",
        "",
        "---",
        "",
        skill.strip(),
        "",
    ]
    for filename, title in ORDER:
        body = (SKILL / "references" / filename).read_text(encoding="utf-8")
        body = re.sub(r"^# .*\n", "", body, count=1)          # drop the file's own H1
        body = re.sub(r"^Read this.*\n", "", body, flags=re.M) # drop the "read this at" line
        parts += ["---", "", f"## Appendix: {filename[:-3]}", "", demote(body.strip()), ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(parts).rstrip() + "\n"
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text):,} chars, {text.count(chr(10)) + 1:,} lines)")
    make_zip()

if __name__ == "__main__":
    main()
